[build]
  command = "npm run build"
  publish  = "dist"

[[redirects]]
  from = "/webhook/*"
  to   = "https://primary-production-fe14.up.railway.app/webhook/:splat"
  status = 200
  force  = true

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
